openapi: 3.1.0
info:
  title: Kinopoisk API
  description: API for Kinopoisk.
  version: 1.0.0

paths:
  '/users':
    $ref: ./paths/users.yaml

  '/users/{userId}':
    $ref: ./paths/users_{userId}.yaml
    
  '/user/{userId}/reviews':
    $ref: ./paths/users_{userId}_reviews.yaml

  '/user/{userId}/reviews/{reviewId}':
    $ref: ./paths/users_{userId}_reviews_{reviewId}.yaml
          
  '/films':
    $ref: ./paths/films.yaml
  
  '/films/{filmsId}':
    $ref: ./paths/films_{filmsId}.yaml

  '/films/{filmId}/reviews':
    $ref: ./paths/films_{filmId}_reviews.yaml
  
  '/films/{filmId}/reviews/{reviewId}':
    $ref: ./paths/films_{filmId}_reviews_{reviewId}.yaml

  '/person':
    $ref: ./paths/person.yaml
            
  '/person/{personId}':
    $ref: ./paths/person_{personId}.yaml

  '/list':
    $ref: ./paths/list.yaml

  '/list/{listId}':
    $ref: ./paths/list_{listId}.yaml

components:
  securitySchemes:
    main_auth:
      description: "Example description text of the OAuth2 scheme."
      type: oauth2
      flows:
        implicit:
          authorizationUrl: http://example.com/api/oauth/dialog
          scopes:
            'read:users': read user info
            'write:users': modify or remove users
    api_key:
      description: "Example description text of the API key scheme."
      type: apiKey
      in: header
      name: api_key
    basic_auth:
      type: http
      scheme: basic